// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Tea from "./Tea.res.js";
import * as Primitive_object from "@rescript/runtime/lib/es6/Primitive_object.js";

function init() {
  let model_selectedFeatures = [];
  let model = {
    selectedEngine: undefined,
    selectedFeatures: model_selectedFeatures,
    showComparison: false,
    configPreview: ""
  };
  return [
    model,
    Tea.Cmd.none
  ];
}

function engineName(engine) {
  switch (engine) {
    case "CasketSSG" :
      return "Casket-SSG";
    case "HackenbushSSG" :
      return "Hackenbush-SSG";
    case "BunseniteSSG" :
      return "Bunsenite-SSG";
    case "CobaltSSG" :
      return "Cobalt-SSG";
  }
}

function engineLanguage(engine) {
  switch (engine) {
    case "CasketSSG" :
      return "Haskell";
    case "HackenbushSSG" :
      return "ReScript";
    case "BunseniteSSG" :
      return "Nickel";
    case "CobaltSSG" :
      return "Rust";
  }
}

function engineFeatures(engine) {
  switch (engine) {
    case "CasketSSG" :
      return [
        "Markdown",
        "AsciiDoc",
        "ReStructuredText",
        "OrgMode",
        "A2ML",
        "K9SvcValidation",
        "Pandoc",
        "SpellCheck",
        "I18n"
      ];
    case "BunseniteSSG" :
      return [
        "Markdown",
        "A2ML"
      ];
    case "HackenbushSSG" :
    case "CobaltSSG" :
      return [
        "Markdown",
        "A2ML",
        "K9SvcValidation"
      ];
  }
}

function featureName(feature) {
  switch (feature) {
    case "Markdown" :
      return "Markdown";
    case "AsciiDoc" :
      return "AsciiDoc";
    case "ReStructuredText" :
      return "reStructuredText";
    case "OrgMode" :
      return "Org-mode";
    case "A2ML" :
      return "a2ml (typed content)";
    case "K9SvcValidation" :
      return "k9-svc (validation)";
    case "I18n" :
      return "i18n";
    case "SpellCheck" :
      return "Spell checking";
    case "Pandoc" :
      return "Pandoc integration";
  }
}

function generateConfig(engine, features) {
  let configHeader = "(k9-svc-validated-config\n  (engine \"" + engineName(engine) + "\")\n";
  let featureList = features.map(f => "  (feature \"" + featureName(f) + "\")").join("\n");
  return configHeader + featureList + "\n  (validation proven))";
}

function update(model, msg) {
  if (typeof msg !== "object") {
    if (msg !== "GenerateConfig") {
      return [
        {
          selectedEngine: model.selectedEngine,
          selectedFeatures: model.selectedFeatures,
          showComparison: !model.showComparison,
          configPreview: model.configPreview
        },
        Tea.Cmd.none
      ];
    }
    let engine = model.selectedEngine;
    if (engine === undefined) {
      return [
        model,
        Tea.Cmd.none
      ];
    }
    let config = generateConfig(engine, model.selectedFeatures);
    return [
      {
        selectedEngine: model.selectedEngine,
        selectedFeatures: model.selectedFeatures,
        showComparison: model.showComparison,
        configPreview: config
      },
      Tea.Cmd.none
    ];
  } else {
    if (msg.TAG === "SelectEngine") {
      let engine$1 = msg._0;
      return [
        {
          selectedEngine: engine$1,
          selectedFeatures: engineFeatures(engine$1),
          showComparison: model.showComparison,
          configPreview: model.configPreview
        },
        Tea.Cmd.none
      ];
    }
    let feature = msg._0;
    let newFeatures = model.selectedFeatures.includes(feature) ? model.selectedFeatures.filter(f => f !== feature) : model.selectedFeatures.concat([feature]);
    return [
      {
        selectedEngine: model.selectedEngine,
        selectedFeatures: newFeatures,
        showComparison: model.showComparison,
        configPreview: model.configPreview
      },
      Tea.Cmd.none
    ];
  }
}

function viewEngineCard(engine, isSelected) {
  return Tea.Html.div([Tea.Html.class$p(isSelected ? "engine-card selected" : "engine-card")], [
    Tea.Html.h4([], [Tea.Html.text(engineName(engine))]),
    Tea.Html.p([], [Tea.Html.text("Language: " + engineLanguage(engine))]),
    Tea.Html.p([], [Tea.Html.text(engineFeatures(engine).length.toString() + " features")])
  ]);
}

function view(model) {
  let engine = model.selectedEngine;
  return Tea.Html.div([Tea.Html.id("tea-app")], [
    Tea.Html.section([Tea.Html.class$p("engine-selector")], [
      Tea.Html.h2([], [Tea.Html.text("Choose Your SSG Engine")]),
      Tea.Html.div([Tea.Html.class$p("engine-grid")], [
        viewEngineCard("CasketSSG", Primitive_object.equal(model.selectedEngine, "CasketSSG")),
        viewEngineCard("HackenbushSSG", Primitive_object.equal(model.selectedEngine, "HackenbushSSG")),
        viewEngineCard("BunseniteSSG", Primitive_object.equal(model.selectedEngine, "BunseniteSSG")),
        viewEngineCard("CobaltSSG", Primitive_object.equal(model.selectedEngine, "CobaltSSG"))
      ]),
      engine !== undefined ? Tea.Html.div([Tea.Html.class$p("features-list")], [
          Tea.Html.h3([], [Tea.Html.text("Available Features")]),
          Tea.Html.div([], model.selectedFeatures.map(feature => Tea.Html.p([], [Tea.Html.text("✓ " + featureName(feature))]))),
          Tea.Html.pre([Tea.Html.class$p("k9-svc-proof")], [
            Tea.Html.text("(k9-svc engine-compatibility\n"),
            Tea.Html.text("  (engine " + engineName(engine) + ")\n"),
            Tea.Html.text("  (features " + model.selectedFeatures.length.toString() + ")\n"),
            Tea.Html.text("  (validated true))")
          ])
        ]) : Tea.Html.p([], [Tea.Html.text("Select an engine above to see features")])
    ]),
    model.configPreview !== "" ? Tea.Html.section([Tea.Html.class$p("config-preview")], [
        Tea.Html.h3([], [Tea.Html.text("Generated Configuration (a2ml)")]),
        Tea.Html.pre([Tea.Html.class$p("a2ml-config")], [Tea.Html.text(model.configPreview)])
      ]) : Tea.Html.noNode
  ]);
}

function subscriptions(_model) {
  Tea.Sub.none;
}

function main() {
  Tea.App.standardProgram({
    init: init,
    update: update,
    view: view,
    subscriptions: subscriptions
  });
}

document.addEventListener("DOMContentLoaded", () => main());

export {
  init,
  engineName,
  engineLanguage,
  engineFeatures,
  featureName,
  generateConfig,
  update,
  viewEngineCard,
  view,
  subscriptions,
  main,
}
/*  Not a pure module */
