// Generated by ReScript, PLEASE EDIT WITH CARE


function init() {
  return {
    selectedEngine: "CasketSSG",
    configOutput: ""
  };
}

function engineName(engine) {
  switch (engine) {
    case "CasketSSG" :
      return "Casket SSG";
    case "HackenbushSSG" :
      return "Hackenbush SSG";
    case "BunseniteSSG" :
      return "Bunsenite SSG";
    case "CobaltSSG" :
      return "Cobalt SSG";
  }
}

function engineFeaturesString(engine) {
  switch (engine) {
    case "CasketSSG" :
      return "Markdown AsciiDoc A2ML k9-svc Pandoc";
    case "HackenbushSSG" :
      return "Markdown TOML Fast";
    case "BunseniteSSG" :
      return "Nickel Type-safe Functional";
    case "CobaltSSG" :
      return "Markdown Liquid Ruby";
  }
}

function generateConfig(engine) {
  let name = engineName(engine);
  let features = engineFeaturesString(engine);
  return "(ssg-config\n  (engine \"" + name + "\")\n  (features [" + features + "]))\n";
}

function update(model, msg) {
  if (typeof msg === "object") {
    return {
      selectedEngine: msg._0,
      configOutput: model.configOutput
    };
  }
  let config = generateConfig(model.selectedEngine);
  return {
    selectedEngine: model.selectedEngine,
    configOutput: config
  };
}

function render(model) {
  let configLen = model.configOutput.length;
  return "poly-ssg - Engine: " + engineName(model.selectedEngine) + " | Config: " + (
    configLen > 0 ? "Generated" : "Not yet"
  );
}

export {
  init,
  engineName,
  engineFeaturesString,
  generateConfig,
  update,
  render,
}
/* No side effect */
